Split utils into separate files for organisation. Rejigged the install process slightly to better cater for already downloaded dotfiles. Added steps to the OS update methods

diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,134 +5,32 @@
 # Variables
 
 declare -r origin="git@github.com:mattkingston/dotfiles.git"
+declare -r installDir="$HOME/projects/dotfiles"
 
 if [[ -d "$(dirname $BASH_SOURCE[0])/os" ]]; then
     declare -r tarballUrl="$(dirname $BASH_SOURCE[0])"
+    declare extracted="YES"
 else
     declare -r tarballUrl="http://github.com/mattkingston/dotfiles/tarball/master"
-fi
-
-if [[ -d "$(dirname $BASH_SOURCE[0])/os" ]]; then
-   declare -r installDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-   declare extracted=1
-else
-    declare -r installDir="$HOME/projects/dotfiles"
-    declare extracted=0
+    declare extracted="NO"
 fi
 
 declare -a argumentList=( "$@" )
-declare argumentListLength=$(expr ${#argumentList[@]} - 1)
+declare -r argumentListLength=$(expr ${#argumentList[@]} - 1)
+
 declare isProxySupplied="NO"
 declare suppliedProxy=""
-declare DEBUG="NO"
+
+declare debug="NO"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 # Definitions
 
-mask_string() {
-    local raw="$1"
-    echo ${raw:0:1}$( echo "${raw:1: -1}" | tr [:print:] \* )${raw: -1}
-}
-
-full_mask_string() {
-    local raw="$1"
-    echo $raw | tr [:print:] \*
-}
-
-is_http() {
-    local url="$1"
-
-    [[ "$url" == "http"* ]] \
-        && return 0
-
-    return 1
-}
-
-is_archive() {
-    local file="$1"
-
-    [[ -f "$file" && "$file" == *".tar"* ]] \
-        && return 0
-
-    return 1
-}
-
-get_os() {
-    local osName="$(uname -s)"
-    local os=''
-
-    if [ "$osName" == "Darwin" ]; then
-        os='osx'
-    elif [ "$osName" == "Linux" ] && [ -e "/etc/lsb-release" ]; then
-        os='ubuntu'
-    else
-        os="$osName"
-    fi
-
-    printf "%s" "$os"
-}
-
-download() {
-    local url="$1"
-    local archive="$2"
-
-    if command -v 'curl' &> /dev/null; then
-        curl -LksSo "$archive" "$url" &> /dev/null
-
-        return $?
-    elif command -v 'wget' &> /dev/null; then
-        wget --no-check-certificate -qO "$archive" "$url" &> /dev/null
-        return $?
-    fi
-
-    return 1
-}
-
-extract() {
-    local archive="$1"
-    local outputDir="$2"
-
-    if command -v 'tar' &> /dev/null; then
-        tar -zxf "$archive" --strip-components 1 -C "$outputDir"
-        return $?
-    fi
-
-    return 1
-}
-
-download_and_extract() {
-    local url="$1"
-    local tmpFile="$2"
-    local tmpDir="$3"
-
-    if is_http "$url"; then
-        if download "$url" "$tmpFile"; then
-            if extract "$tmpFile" "$tmpDir"; then
-                return 0
-            fi
-        fi
-    else
-        if is_archive "$url"; then
-            cp "$url" "$tmpFile"
-
-            if extract "$tmpFile" "$tmpDir"; then
-                return 0
-            fi
-        elif [[ -d "$url" ]]; then
-            if cp -r "$url/." "$tmpDir/"; then
-                return 0
-            fi
-        fi
-    fi
-
-    return 1
-}
-
 main() {
 
-    declare workingDirectory="$(pwd)" \
-        && cd "$(dirname $BASH_SOURCE[0])"
+    local workingDirectory="$(pwd)" \
+      && cd "$(dirname $BASH_SOURCE[0])"
 
     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
@@ -145,10 +43,40 @@ main() {
 
     # Download dotfiles to a temporary location
 
-    if [[ "$extracted" -eq 1 ]]; then
+    if [[ "$extracted" == "YES" ]]; then
         source "$installDir/shell/bash_utils"
     else
-        download_and_extract "$tarballUrl" "$tmpFile" "$tmpDir"
+
+        if [[ "$tarballUrl" == "http"* ]]; then
+            if command -v 'curl' &> /dev/null; then
+                curl -LksSo "$tmpFile" "$tarballUrl" &> /dev/null \
+                  || echo "Download failed" && exit 1
+            elif command -v 'wget' &> /dev/null; then
+                wget --no-check-certificate -qO "$tmpFile" "$tarballUrl" &> /dev/null \
+                  || echo "Download failed" && exit 1
+            else
+                echo "curl or wget required. Cannot continue" && exit 1
+            fi
+
+            if command -v 'tar' &> /dev/null; then
+                tar -zxf "$tmpFile" --strip-components 1 -C "$tmpDir" \
+                  || echo "Tar extraction failed" && exit 1
+            fi
+        else
+            if [[ -f "$tarballUrl" && "$tarballUrl" == *".tar"* ]]; then
+                cp "$tarballUrl" "$tmpFile"
+
+                if command -v 'tar' &> /dev/null; then
+                    tar -zxf "$tmpFile" --strip-components 1 -C "$tmpDir" \
+                      || echo "Tar extraction failed" && exit 1
+                fi
+            elif [[ -d "$tarballUrl" ]]; then
+                if cp -r "$tarballUrl/." "$tmpDir/"; then
+                    return 0
+                fi
+            fi
+        fi
+
         source "$tmpDir/shell/bash_utils"
     fi
 
@@ -161,85 +89,68 @@ main() {
     ask_for_sudo
 
     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-    
-    if [[ "$extracted" -eq 1 ]]; then
-        # The tarball has been downloaded and extracted already
-        
-        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-        newInstallDir="$installDir"
+    # Ask where to store the dotfiles binaries
 
-        cd "$newInstallDir"
-        
-    else
+    ask_for_confirmation "Do you want to store the base dotfiles in '$newInstallDir'?"
 
-        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+    if ! answer_is_yes; then
+      newInstallDir=''
 
-        # Ask where to store the dotfiles binaries
+      while [[ -z "$newInstallDir" || "$newInstallDir" == "" ]]; do
+        ask 'Please specify another location for the base dotfiles (absolute path): '
 
-        ask_for_confirmation "Do you want to store the base dotfiles in '$newInstallDir'?"
+        newInstallDir="$(get_answer)"
+      done
+    fi
 
-        if ! answer_is_yes; then
-          newInstallDir=''
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-          while [[ -z "$newInstallDir" || "$newInstallDir" == "" ]]; do
-            ask 'Please specify another location for the base dotfiles (absolute path): '
+    # Request overwrite of the directory
 
-            newInstallDir="$(get_answer)"
-          done
-        fi
+    while [[ -e "$newInstallDir" ]]; do
+      ask_for_confirmation "'$newInstallDir' already exists, do you want to overwrite it?"
 
-        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+      if answer_is_yes; then
+        rm -rf "$newInstallDir"
+        break
+      else
+        newInstallDir=''
 
-        # Request overwrite of the directory
+        while [[ -z "$newInstallDir" || "$newInstallDir" == "" ]]; do
+          ask 'Please specify another location for the base dotfiles (absolute path): '
 
-        while [[ -e "$newInstallDir" ]]; do
-          ask_for_confirmation "'$newInstallDir' already exists, do you want to overwrite it?"
+          newInstallDir="$(get_answer)"
 
-          if answer_is_yes; then
-            rm -rf "$newInstallDir"
-            break
-          else
-            newInstallDir=''
-
-            while [[ -z "$newInstallDir" || "$newInstallDir" == "" ]]; do
-              ask 'Please specify another location for the base dotfiles (absolute path): '
-
-              newInstallDir="$(get_answer)"
-
-              if [[ -z "$newInstallDir" || "$newInstallDir" == "" ]]; then
-                newInstallDir="$installDir"
-              fi
-            done
-
+          if [[ -z "$newInstallDir" || "$newInstallDir" == "" ]]; then
+            newInstallDir="$installDir"
           fi
         done
 
-        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+      fi
+    done
 
-        # Move the downloaded dotfiles to the selected directory
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-        if [[ ! -e "$newInstallDir" ]]; then
-          mkdir -p "$(dirname $newInstallDir)"
+    # Move the downloaded / copy the existing dotfiles to the selected directory
 
-          mv "$tmpDir" "$newInstallDir"
+    if [[ ! -e "$newInstallDir" ]]; then
+      mkdir -p "$(dirname $newInstallDir)"
 
-          print_result $? "Create '$newInstallDir'"
-        fi
+      print_result $? "Create '$newInstallDir'"
 
-        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+      mv "$tmpDir" "$newInstallDir"
 
-        # Remove archive
+      # Remove archive
 
-        rm -rf "$tmpFile"
+      rm -rf "$tmpFile"
 
-        print_result  $? "Remove archive $(print_in_grey "($tmpFile)")"
-
-        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-        cd "$newInstallDir"
-
+      print_result  $? "Remove archive $(print_in_grey "($tmpFile)")"
     fi
+
+    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+    cd "$newInstallDir"
 
     # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
